series: Basic C++
title: Pointer Casting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: C++ provides some helpful functions for casting between different types of pointers.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Virtual Functions